export class Products {
    public products = [{
      "ID": 1,
      "Name": "Hydrogen",
      "Price": 330,
      "Current_Inventory": 225,
      "Backorder": 0,
      "Manufacturing": 10,
      "Category": "Video Players",
      "ImageSrc": "images/products/1.png"
  }, {
      "ID": 3,
      "Name": "Helium",
      "Price": 2400,
      "Current_Inventory": 0,
      "Backorder": 0,
      "Manufacturing": 0,
      "Category": "Televisions",
      "ImageSrc": "images/products/3.png"
  }, {
      "ID": 4,
      "Name": "Lithium",
      "Price": 1600,
      "Current_Inventory": 77,
      "Backorder": 0,
      "Manufacturing": 55,
      "Category": "Televisions",
      "ImageSrc": "images/products/4.png"
  }, {
      "ID": 5,
      "Name": "Beryllium",
      "Price": 1450,
      "Current_Inventory": 445,
      "Backorder": 0,
      "Manufacturing": 0,
      "Category": "Televisions",
      "ImageSrc": "images/products/5.png"
  }, {
      "ID": 6,
      "Name": "Boron",
      "Price": 1350,
      "Current_Inventory": 345,
      "Backorder": 0,
      "Manufacturing": 5,
      "Category": "Televisions",
      "ImageSrc": "images/products/6.png"
  }, {
      "ID": 7,
      "Name": "Carbon",
      "Price": 1200,
      "Current_Inventory": 210,
      "Backorder": 0,
      "Manufacturing": 20,
      "Category": "Televisions",
      "ImageSrc": "images/products/7.png"
  }, {
      "ID": 8,
      "Name": "Nitrogen",
      "Price": 3500,
      "Current_Inventory": 0,
      "Backorder": 0,
      "Manufacturing": 0,
      "Category": "Televisions",
      "ImageSrc": "images/products/8.png"
  }, {
      "ID": 9,
      "Name": "Oxygen",
      "Price": 4000,
      "Current_Inventory": 95,
      "Backorder": 0,
      "Manufacturing": 5,
      "Category": "Televisions",
      "ImageSrc": "images/products/9.png"
  }, {
      "ID": 10,
      "Name": "Fluorine",
      "Price": 175,
      "Current_Inventory": null,
      "Backorder": 425,
      "Manufacturing": 75,
      "Category": "Monitors",
      "ImageSrc": "images/products/10.png"
  }, {
      "ID": 12,
      "Name": "Neon",
      "Price": 170,
      "Current_Inventory": 210,
      "Backorder": 0,
      "Manufacturing": 60,
      "Category": "Monitors",
      "ImageSrc": "images/products/12.png"
  }];
  }